app:
  jwt:
    secret: asvUp19m2wq/E+rWWVaLxpXmZ+I0d75PuWTvDUMI3tM=

#logging:
#  level:
#    root: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      connection:
        handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
      ddl-auto: none
      hibernate:
        transaction:
          factory_class: bitronix.tm.BitronixTransactionManager
      transaction:
        coordinator_class: jta
    show-sql: true
  jta:
    bitronix:
      datasource:
        local-auto-commit: false
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath*:schema.sql
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    template:
      exchange: amq.topic
      routing-key: mailbox
  mqtt:
    username: guest
    password: guest
    url: tcp://127.0.0.1:1883
    client:
      id: main-service
    default:
      topic: mailbox
    completionTimeout: 3000
